### ISSUE TITLE
notice a mit license clause

### ISSUE THREAD

**Issue by PooiaFerdowsi** [mehanalavimajd/panix#1]
```
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or **(note here)sell**
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
```

at first glance it's is ordinary for MIT LICENSE but in a closer look a attracts attention.
***sell***
this means any one can sell it with out *any* difference!
so if you want prevent it remove *self* and add following clause in LICENSE file

```
mit license with a restriction:
you can't sell
```

**Comment by mehanalavimajd** [comment]
Thanks for informing me . 
I would search to find a better license .

**Comment by mehanalavimajd** [comment]
Hi there @PooiaFerdowsi  . I couldn't find any other license (Apache 2.0 was really hard to read).
so I started to make my own license:
`
copyright 2021 panixjs 
Permission is hereby granted that everybody can use , copy , change and publish this software with accepting following conditions :
1- Although you can publish this software , you cannot sell and trade this software .
2- every software that is copying from this software (even one line) , should use this license .
3- This software is provided without any kind of Warranty .
4- The Authors or copyright holders are not liable for any damages or any kind of liability.
`
The reason that didn't write "panix" in top was that there is a company called "panix"
is it ok?

**Comment by PooiaFerdowsi** [comment]
it's good but as an English note mentioned at line 2 
`should` is different of `must` should means better but must means you enforced, you compel

1. firefighter: when a big fire occurs 
... you must escape
2. Doctor: to ill
you should drink water lot

noticed that firefighter `enforced` peoples to escape but doctor offered!

**Comment by mehanalavimajd** [comment]
You are right . Thanks for informing me :)

**Comment by mehanalavimajd** [comment]
24d76b4d10560c9fb476bfff096cb07ce2333782
