### ISSUE TITLE
Style function

### ISSUE THREAD

**Issue by mehanalavimajd** [mehanalavimajd/panix#2]
@PooiaFerdowsi I think we should make a style funcion that is like this :
```js
{
fontWeight:600,
color:red
} 
// to this 
["fontStyle : 600 ;" , "color : red"]
```

**Comment by mehanalavimajd** [comment]
and also we should make an styleHtml  that does the same thing but create a style attribute

**Comment by mehanalavimajd** [comment]
c9a2db7ff422ac0075aa070ee2af5e09f9e077d8

**Comment by mehanalavimajd** [comment]
also , @PooiaFerdowsi , you can create styleHtml by yourself if you want

**Comment by PooiaFerdowsi** [comment]
I have no idea!
