### ISSUE TITLE
cannot pass null as props

### ISSUE THREAD

**Issue by mehanalavimajd** [mehanalavimajd/panix#5]
I usually pass {} for props but this time I used null and  it didn't work . I will work on it today or tomorrow.
also @PooiaFerdowsi do you know any body who can contribute?

**Comment by PooiaFerdowsi** [comment]
Yes but no much, GitHub usernames.
<https://github.com/amirghazi87>
<https://github.com/AshkanLaei>

And, I suggest remove directories in `src` directory, e.g. change `src/style/style.js` to `src/style.js`

**Comment by mehanalavimajd** [comment]
I know them but I have already told to  contribute if they want . but the don't answer my email . 
If we remove directories won't the src dir become untidy?

**Comment by PooiaFerdowsi** [comment]
even when each directory contain only 1 file? `src` dir become unitdy?

**Comment by mehanalavimajd** [comment]
No But because I'm going to add some utils to each dir. And I going to mix style html and style .
