### ISSUE TITLE
Running mount function

### ISSUE THREAD

**Issue by mehanalavimajd** [mehanalavimajd/panix#6]
our Syntax is this:
```js
mount(node("div" , {id:"hello"} , "hello world"))
```
That's fine but if we want to assign a variable : 
```js
let a = mount(node("div" , {id:"hello"} , "hello world"))
```
it will run again !!!
my idea is this : 
```js
let a = mount(node("div" , {id:"hello"} , "hello world"))
a.run()
```
and if we want to run it without declare a variable 
```
mount(node("div" , {id:"hello"} , "hello world")).run()
```
do you agree @pooiaFerdowsi and @amirGhazi87

**Comment by PooiaFerdowsi** [comment]
Your framework syntax is not as much as never change it important.

A good framework should implement somethings you know! now, check if this choice increase development time [etc]

It is more important than your framework syntax

**Comment by mehanalavimajd** [comment]
I didn't understand did you agree or not but I think this edit would just take 1 or 2 hours

**Comment by PooiaFerdowsi** [comment]
I agree!

**Comment by mehanalavimajd** [comment]
OK also if want to access to element data we make something like this :
```js
let a = mount(node("div" , {id:"hello"} , "hello world"))
console.log(a.element.id) // hello
```

**Comment by mehanalavimajd** [comment]
I found a bug ; if we want to make another mount in our mount we must run automatically but maybe user don't want this :( .
also our syntax is getting harder and more user-friendly.
I will close the issue.
